version: "3"
services:
  app:
    container_name: spotify-user-matching-client
    # image: node:16-alpine
    image: public.ecr.aws/b6w3b5r6/all-time-music-ranking-client:latest
    volumes:
      - ./:/app
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
