version: "3"

services:
  api:
    container_name: spotify-user-matching-server
    build: ./docker/uvicorn
    restart: always
    tty: true
    ports:
      - 8001:8000
    volumes:
      - ./api:/usr/src/api
