services:
  api:
    container_name: spotify-user-matching-server
    build: ./docker/uvicorn
    restart: always
    tty: true
    ports:
      - 8001:8000
    volumes:
      - ./api:/usr/src/api
    depends_on:
      - db
  db:
    image: postgres:11-alpine
    container_name: spotify-user-matching-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=spotify-user-matching-db
